# Generated by Django 3.1.5 on 2022-02-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.TextField()),
                ('description', models.TextField()),
                ('dateCreation', models.DateField(null=True)),
                ('latitudeLieuTravail', models.TextField(default='Non renseigné')),
                ('longitudeLieuTravail', models.TextField(default='Non renseigné')),
                ('nomLieuTravail', models.TextField(default='Non renseigné')),
                ('entreprise', models.TextField(default='Non renseigné')),
                ('typeContrat', models.TextField(default='Non renseigné')),
                ('experienceExigee', models.TextField(default='Non renseigné')),
                ('salaire', models.TextField(default='Non renseigné')),
                ('dureeTravail', models.TextField(default='Non renseigné')),
                ('rythmeTravail', models.TextField(default='Non renseigné')),
                ('alternance', models.TextField(default='Non renseigné')),
                ('nomContact', models.TextField(default='Non renseigné')),
                ('qualification', models.TextField(default='Non renseigné')),
                ('qualitesPro', models.TextField(default='Non renseigné')),
                ('origineOffre', models.TextField(default='Non renseigné')),
                ('provenance', models.TextField()),
                ('lang_detect', models.TextField()),
            ],
        ),
    ]
