# Generated by Django 3.1.5 on 2022-02-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_pole_nbskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='matchedSkills',
            field=models.TextField(default=' '),
        ),
    ]
